app = '23-112'

[build]

# هذا السطر يمنع المنصة من إطفاء البوت نهائياً
min_machines_running = 1

[[services]]
  internal_port = 3000
  protocol = "tcp"
  # هذه الإعدادات تمنع "النوم" التلقائي
  auto_stop_machines = false
  auto_start_machines = true

[[vm]]
  memory = '256mb'
  memory_mb = 256
