# fly.toml app configuration file generated for lml10l-x7pzyw on 2026-01-30T20:01:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lml10l-x7pzyw'
primary_region = 'iad'

[build]


  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
